clc
clear 
close all

T = [298.15; 300.00; 400.00; 500.00; 600.00; 700.00; 800.00; 900.00; 1000.0;
     1100.0; 1200.0; 1300.0; 1400.0; 1500.0; 1600.0; 1700.0; 1800.0; 1900.0; 
     2000.0; 2100.0; 2200.0; 2300.0; 2327.0];
Cp = [79.038; 79.434; 96.117; 106.142; 112.552; 116.956; 120.179; 122.667; 
      124.753; 126.614; 128.267; 129.743; 131.069; 132.273; 133.375; 134.262;
      135.091; 135.874; 136.619; 137.334; 138.024; 138.693; 138.871];


%CREATEFIT(T,CP)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input: T
%      Y Output: Cp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Nov-2022 10:16:30


%% Fit: 'untitled fit 2'.
% [xData, yData] = prepareCurveData( T, Cp );
% 
% % Set up fittype and options.
% ft = fittype( 'power2' );
% opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
% opts.Display = 'Off';
% opts.StartPoint = [8.17048523047082 0.386575587868082 -2.72129841847769];
% 
% % Fit model to data.
% [fitresult, gof] = fit( xData, yData, ft, opts );


% ---------
 [xData, yData] = prepareCurveData( T, Cp );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% ---------

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult, xData, yData );
legend( h, 'Cp vs. T', 'Fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'T [K]', 'Interpreter', 'none' );
ylabel( 'Cp [J/mol K]', 'Interpreter', 'none' );
grid on