clc
clear 
close all

T = [298.15; 300.00; 400.00; 500.00; 600.00; 700.00; 800.00; 900.00; 1000.0;
     1100.0; 1200.0; 1300.0; 1400.0; 1500.0; 1600.0; 1700.0; 1726.0];
Cp = [26.067; 26.100; 28.467; 30.863; 34.772; 30.835; 31.129; 31.966; 32.966;
      33.927; 34.888; 35.723; 36.181; 36.192; 36.192; 36.192; 36.192];

%  Data for 'untitled fit 5' fit:
%      X Input: T
%      Y Output: Cp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Nov-2022 11:00:54


%% Fit: 'untitled fit 5'.
[xData, yData] = prepareCurveData( T, Cp );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 5' );
h = plot( fitresult, xData, yData );
legend( h, 'Cp vs. T', 'FIT', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'T [K]', 'Interpreter', 'none' );
ylabel( 'Cp [J/mol K]', 'Interpreter', 'none' );
grid on