clc
clear 
close all

T = [10; 20; 40; 60; 80; 100; 200; 300; 400; 500; 600; 800; 1000; 1200; 1400];
tc = [2600; 1700; 570; 290; 200; 158; 106; 91; 80; 72; 66; 67; 72; 76; 80];

%  Data for 'untitled fit 5' fit:
%      X Input: T
%      Y Output: Cp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Nov-2022 11:00:54


%% Fit: 'untitled fit 5'.
[xData, yData] = prepareCurveData( T, tc );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft);

% Plot fit with data.
figure( 'Name', 'untitled fit 5' );
h = plot( fitresult, xData, yData );
legend( h, 'thermal conductivity vs. T', 'FIT', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'T [K]', 'Interpreter', 'none' );
ylabel( 'thermal conductivity [W / m K]', 'Interpreter', 'none' );
grid on